import { Inter } from "next/font/google";
import "./globals.css";
import { UserAuthContextProvider } from "./context/userAuthContext";
import {NextUIProvider} from '@nextui-org/react'
const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Eunom.ai",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
       
      <UserAuthContextProvider>
      

      <body 
      className={inter.className}
      >
      <NextUIProvider>
        {children}
        </NextUIProvider>
        </body>
       
      </UserAuthContextProvider>
      
    </html>
  );
}
